export const DEFAULT_REMOTE_PORT = 22;
export const REMOTE_HOME_ROOT = '/home';

export const DEFAULT_INCLUDE_GLOBS: string[] = [];

export const DEFAULT_EXCLUDE_GLOBS = [
  '**/.git/**',
  '**/.svn/**',
  '**/.hg/**',
  '**/.*/**',
  '**/.cache/**',
  '**/__pycache__/**',
  '**/.gradle/**',
  '**/.idea/**',
  '**/.vscode/**',
  '**/.vs/**',
  '**/.settings/**',
  '**/.DS_Store',
  '**/*.7z',
  '**/*.a',
  '**/*.apk',
  '**/*.bin',
  '**/*.bz2',
  '**/*.class',
  '**/*.dll',
  '**/*.dmg',
  '**/*.ear',
  '**/*.exe',
  '**/*.gz',
  '**/*.ico',
  '**/*.jar',
  '**/*.jpg',
  '**/*.jpeg',
  '**/*.lib',
  '**/*.min.js.map',
  '**/*.min.css.map',
  '**/*.mp3',
  '**/*.mp4',
  '**/*.o',
  '**/*.obj',
  '**/*.otf',
  '**/*.pdf',
  '**/*.pdb',
  '**/*.png',
  '**/*.pyc',
  '**/*.rar',
  '**/*.so',
  '**/*.svgz',
  '**/*.tar',
  '**/*.tgz',
  '**/*.ttf',
  '**/*.war',
  '**/*.webp',
  '**/*.woff',
  '**/*.woff2',
  '**/*.xz',
  '**/*.zip'
];
